trigger:
  - main  

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Checkout the repository
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: SonarQubePrepare@7
    inputs:
      SonarQube: 'qonda-service-connection'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'AIContextAssistant_AIContextAssistant_b855511c-2fdb-4fbd-8ce4-615deecb6b83'
    
  - task: SonarQubeAnalyze@7
   

  - task: SonarQubePublish@7
    inputs:
      pollingTimeoutSec: '300'